version: '3'
services:
  db:
    image: 'postgres:9.6'
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./dockerfiles/postgresql.conf:/etc/postgresql.conf
    ports:
      - 127.0.0.1:5434:5432
    command: postgres -c config_file=/etc/postgresql.conf

  datachile-mondrian:
    image: 'datachile-mondrian:0.7.2'
    environment:
      - APP_HOME=/datachile/
      - MONDRIAN_REST_CONF=/datachile-mondrian.yaml
      - VIRTUAL_HOST=chilecube.datawheel.us
      - LETSENCRYPT_HOST=chilecube.datawheel.us
      - LETSENCRYPT_EMAIL=datachile@datawheel.us
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./dockerfiles/datachile-mondrian.yaml:/datachile-mondrian.yaml
    ports:
      - 127.0.0.1:9393:9292

  datachile-canon:
    build:
      context: .
      dockerfile: dockerfiles/datachile-canon.dockerfile
    environment:
      - NODE_ENV=production
      - CANON_PORT=4444
      - ROOT=/datachile
      - CANON_API=https://chilecube.datawheel.us/
      - CANON_GOOGLE_ANALYTICS=UA-########-#
      - CANON_LANGUAGES=es
      - CANON_LANGUAGES_DEFAULT=en
      - APP_HOME=/datachile
      - VIRTUAL_HOST=en.datachile.datawheel.us,es.datachile.datawheel.us,datachile.datawheel.us
      - LETSENCRYPT_HOST=en.datachile.datawheel.us,es.datachile.datawheel.us,datachile.datawheel.us
      - LETSENCRYPT_EMAIL=datachile@datawheel.us
    volumes:
      - canon-static:/datachile/static-shared
    depends_on:
      - datachile-mondrian
    links:
      - datachile-mondrian
    # alias the host IP to the API server
    # because of NATing. should not be necessary in not nat'd networks
    extra_hosts:
      - "chilecube.datawheel.us:172.17.0.1"

  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - canon-static:/datachile-files
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

volumes:
  db-data:
    external:
      name: "datachile_db-data"
  canon-static:
    