version: "3"
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5434:5432
  
  datachile-mondrian:
    image: datachile-mondrian
    environment:
      - APP_HOME=/datachile/
      - MONDRIAN_REST_CONF=/datachile-mondrian.yaml
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./dockerfiles/datachile-mondrian.yaml:/datachile-mondrian.yaml
    ports:
      - 127.0.0.1:9393:9292
  
  datachile-canon:
    build:
      context: .
      dockerfile: dockerfiles/datachile-canon.dockerfile
    environment:
      - NODE_ENV=production
      - CANON_PORT=4444
      - ROOT=/datachile
      - CANON_API=http://chilecube.datawheel.us
      - CANON_GOOGLE_ANALYTICS=UA-########-#
      - CANON_LANGUAGES=es
      - CANON_LANGUAGES_DEFAULT=en
      - APP_HOME=/datachile
    volumes:
      - canon:/datachile
    depends_on:
      - datachile-mondrian
    links:
      - datachile-mondrian
  
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - canon:/datachile-files
  
volumes:
  db-data:
  canon:

